insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (1, 'Drama/Mex', 'Drama', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (2, 'Thunderpants', 'Children|Comedy|Sci-Fi', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (3, 'Me, Myself & Irene', 'Adventure|Comedy', 2007);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (4, 'Hannibal Rising', 'Drama|Horror|Thriller', 1992);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (5, 'Tarnation', 'Documentary', 1995);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (6, 'Patsy, The', 'Comedy', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (7, 'Omen, The', 'Horror|Thriller', 2009);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (8, 'Talk Radio', 'Drama', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (9, 'Nebraska', 'Adventure|Drama', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (10, 'Club Dread', 'Comedy|Horror', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (11, 'Space Station 76', 'Comedy|Drama|Sci-Fi', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (12, 'The Front', 'Crime|Drama|Mystery', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (13, 'Prey, The (La proie)', 'Action|Crime|Thriller', 1995);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (14, 'The Siege of Firebase Gloria', 'Action|Drama|War', 1991);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (15, 'Bob & Carol & Ted & Alice', 'Comedy|Drama', 1997);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (16, 'Death Ship', 'Horror', 2000);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (17, '11 Flowers (Wo 11)', 'Drama', 2009);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (18, 'Cimarron Kid, The', 'Western', 1990);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (19, 'Old Man Made in Spain (Abuelo made in Spain)', 'Comedy', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (20, 'Man Who Captured Eichmann, The', 'Drama|War', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (21, 'Steamboy (Suchîmubôi)', 'Action|Animation|Drama|Sci-Fi', 2000);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (22, 'Closing the Ring', 'Drama|Romance', 1998);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (23, 'M*A*S*H (a.k.a. MASH)', 'Comedy|Drama|War', 1986);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (24, 'Vatel', 'Drama', 1994);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (25, 'Galaxina', 'Comedy|Sci-Fi', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (26, 'Walk Hard: The Dewey Cox Story', 'Comedy|Musical', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (27, 'Blood, Guts, Bullets and Octane', 'Action|Comedy', 1996);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (28, 'Dangerous Beauty', 'Drama', 1984);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (29, 'Terra (a.k.a. Battle for Terra)', 'Adventure|Animation|Sci-Fi', 1994);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (30, 'White Darkness, The', 'Documentary', 2002);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (31, 'Cromwell', 'Drama', 1995);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (32, 'I Live in Fear (Ikimono no kiroku)', 'Drama', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (33, 'Haunted Castle, The (Schloß Vogeloed)', 'Crime|Drama|Horror|Mystery', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (34, 'Puppet Master: Axis of Evil (Puppet Master 10)', 'Horror', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (35, 'Ouija', 'Horror', 1993);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (36, 'The Invisible Frame', 'Documentary', 2002);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (37, 'In Country', 'Drama', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (38, 'Virus X', 'Horror|Sci-Fi', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (39, 'Flowers of St. Francis (Francesco, giullare di Dio)', 'Drama', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (40, 'Zen Noir', 'Comedy|Drama|Mystery', 1997);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (41, 'Place Promised in Our Early Days, The (Kumo no mukô, yakusoku no basho)', 'Animation|Drama|Romance|Sci-Fi|War', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (42, 'Our Idiot Brother', 'Comedy', 1987);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (43, 'Home of the Brave', 'Documentary', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (44, 'New Fist of Fury (Xin jing wu men)', 'Action|Drama', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (45, 'Three Smart Girls Grow Up', 'Comedy|Musical|Romance', 1992);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (46, 'Respiro', 'Comedy|Drama', 2001);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (47, 'Snakehead Terror', 'Action|Horror|Sci-Fi|Thriller', 1993);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (48, 'Boot Camp', 'Thriller', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (49, 'Headhunters (Hodejegerne)', 'Action|Crime|Thriller', 1996);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (50, 'Windfall', 'Documentary', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (51, 'Pressed', 'Action|Crime|Drama|Thriller', 1998);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (52, 'I Was Monty''s Double', 'Drama|War', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (53, 'Bob le Flambeur', 'Crime|Drama', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (54, 'Reconstituirea (Reconstruction)', 'Comedy|Drama', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (55, 'Vermont Is For Lovers', 'Comedy|Documentary|Romance', 1992);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (56, 'Mrs. Winterbourne', 'Comedy|Romance', 2002);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (57, 'The Challenge', 'Drama|War', 1993);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (58, 'Svengali', 'Drama|Horror', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (59, 'Passion of Love (Passione d''amore)', 'Drama|Romance', 2000);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (60, 'No Greater Love', 'Drama|Romance', 1999);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (61, 'Out Cold', 'Comedy', 1996);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (62, 'Skeleton Twins, The', 'Drama', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (63, 'Muzi v nadeji', 'Comedy|Drama|Romance', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (64, 'The Loft', 'Thriller', 2009);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (65, 'Boomerang', 'Comedy|Romance', 2011);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (66, 'Heart of a Dog (Sobachye serdtse)', 'Comedy|Drama|Sci-Fi', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (67, 'Blue Denim', 'Drama', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (68, 'Being John Malkovich', 'Comedy|Drama|Fantasy', 2013);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (69, 'Zombie and the Ghost Train (Zombie ja Kummitusjuna)', 'Comedy|Drama', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (70, 'Cooking with Stella', 'Drama', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (71, 'Goon', 'Comedy|Drama', 2011);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (72, 'Murder She Said', 'Comedy|Crime|Drama|Mystery', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (73, 'Romance in Manhattan', 'Comedy|Romance', 2002);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (74, 'Fitzcarraldo', 'Adventure|Drama', 1994);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (75, 'Grudge 3, The', 'Horror', 2012);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (76, 'Decoy Bride, The', 'Comedy|Romance', 1988);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (77, 'Murder in Greenwich', 'Crime|Drama|Mystery', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (78, 'Tongan Ninja', 'Action|Adventure|Comedy', 1998);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (79, 'Sex and Lucia (Lucía y el sexo)', 'Drama|Romance', 2008);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (80, 'Max Keeble''s Big Move', 'Children|Comedy', 1998);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (81, 'In Name Only', 'Drama|Romance', 1997);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (82, 'Mixed Blood', 'Action|Drama', 2002);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (83, 'Oxy-Morons', 'Crime|Drama', 2000);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (84, 'Great Muppet Caper, The', 'Children|Comedy', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (85, 'Chernobyl Diaries', 'Horror', 1986);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (86, 'Wicked Lady, The', 'Adventure|Drama', 2006);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (87, 'Shoah', 'Documentary|War', 2007);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (88, 'Party Girl', 'Comedy', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (89, 'Mind Reader, The', 'Drama|Romance', 1995);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (90, 'Go Figure (Va savoir)', 'Comedy|Drama|Romance', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (91, 'Tim''s Vermeer', 'Documentary', 1994);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (92, 'PK', 'Comedy|Drama|Fantasy|Mystery|Romance', 2005);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (93, 'The Boy Who Cried Werewolf', 'Children|Horror', 1996);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (94, 'Feast of Love', 'Drama|Romance', 2011);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (95, 'Valentine', 'Horror|Mystery', 2003);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (96, 'Hangman''s House', 'Drama', 2011);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (97, 'Notorious', 'Film-Noir|Romance|Thriller', 2010);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (98, 'Mr. Wu', 'Drama', 1994);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (99, 'Hi-Line, The', 'Drama', 2004);
insert into tb_movies (id_movie, movie_title, movie_gender, movie_year) values (100, 'Sand Pebbles, The', 'Drama|Romance|War', 2005);
